server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: app-chat
  websocket:
    servlet:
      allowed-origins: "*"
      allow-credentials: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers:
        - localhost:9092
    listener:
      missing-topics-fatal: false